name: my first workflow | shell script
on: 
    push:
        branches:
            - main
jobs:
    build:
        runs-on: self-hosted
        steps:
            - name: echo
              run: echo "CICD"